org.gradle.caching=true
org.gradle.jvmargs=-Xmx4g -Dfile.encoding=UTF-8
kotlin.code.style=official

POM_NAME=detekt-rules
POM_DESCRIPTION=Custom detekt rules by Michael Bel
POM_URL=https://github.com/michaelbel/detekt-rules
POM_SCM_URL=https://github.com/michaelbel/detekt-rules
POM_SCM_CONNECTION=scm:git:https://github.com/michaelbel/detekt-rules.git
POM_SCM_DEVELOPER_CONNECTION=scm:git:ssh://git@github.com/michaelbel/detekt-rules.git
POM_DEVELOPER_ID=michaelbel
POM_DEVELOPER_NAME=Michael Bel
POM_DEVELOPER_URL=https://github.com/michaelbel
POM_LICENSE_NAME=The Apache License, Version 2.0
POM_LICENSE_URL=https://www.apache.org/licenses/LICENSE-2.0.txt
