michaelbel:
  active: true
  ComposableFileOptIn:
    active: true
  ModifierPaddingArgumentOrder:
    active: true
  NoSpaceBeforeInheritanceColon:
    active: true
  PaddingValuesSymmetry:
    active: true
  TextAlignInTextStyle:
    active: true
  SizeModifierWithConstrainAs:
    active: true
